# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = left_forgotten
mod_name = Left Forgotten
mod_version = 1.1.3-alpha.1
mod_description = Once glory days of Minecraft, now buried beneath the void. Minecraft Alpha is still there, but left and abandoned ages ago.
mod_license = All Rights Reserved
mod_authors = JustMili, BluSpring

maven_group = net.justmili.leftforgotten
archives_base_name = LeftForgotten
enabled_platforms = fabric,forge

minecraft_version_constraint_forge = [1.20.1]
minecraft_version_constraint_fabric = 1.20.1
supported_versions = 1.20.1

# Dependencies
corelibs = 1.1.0+mc1.20.1
mod_menu = 7.2.2
cloth_config = 11.1.136
nt_fabric = reUPJIcX
nt_forge = 2.0.0-beta.922