modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/JustMili0/LeftForgotten/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = "${mod_description}"
authors = "JustMili"
credits = "BluSpring, NBSurprise, Eetgeenappels, Cyber-Sammy"
logoFile = "forge_banner.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_constraint}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}-neoforge.mixins.json"