plugins {
    id("com.gradleup.shadow")
}

def generatedResources = file("src/generated")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    //mixin.useLegacyMixinAp = true

    runs {
        data {
            data()
            programArgs "--all", "--mod", "${rootProject.property("mod_id")}"
            programArgs "--output", generatedResources.absolutePath
        }
    }
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    neoForge("${libs.neoforge.get()}")

    // NeoForge dependencies go here
    modImplementation("dev.architectury:architectury-neoforge:${libs.versions.arch.api.get()}")

    modImplementation("maven.modrinth:nostalgic-tweaks:${rootProject.property("nt_neoforge")}")
    modImplementation("me.shedaniel.cloth:cloth-config-neoforge:${rootProject.property("cloth_config")}")

    // NeoForge mainlines MixinExtras since 20.2.84, still requires MixinSquared tho
    compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${libs.versions.mixinsquared.get()}"))
    implementation(include("com.github.bawnorton.mixinsquared:mixinsquared-neoforge:${libs.versions.mixinsquared.get()}"))

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')
}

processResources {
    filesMatching('META-INF/neoforge.mods.toml') {
        expand "mod_id": rootProject.property("mod_id"),
                "mod_name": rootProject.property("mod_name"),
                "mod_version": rootProject.property("mod_version"),
                "mod_description": rootProject.property("mod_description"),
                "mod_authors": rootProject.property("mod_authors"),
                "mod_license": rootProject.property("mod_license"),
                "forge_version": libs.versions.neoforge.get(),
                "minecraft_version_constraint": rootProject.property("minecraft_version_constraint_neoforge"),
                "architectury_api": libs.versions.arch.api.get()
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}